export const Roles = {
    ADMIN: "ADMIN",
    MODERATOR: "MODERATOR",
    EDYTOR: "EDYTOR",
    AUTOR: "AUTOR",
    CZYTELNIK: "CZYTELNIK",
} as const;

export type RoleType = keyof typeof Roles;

export const Permissions = {
    // Artykuły
    ADD_ARTICLE: "ADD_ARTICLE",
    EDIT_ARTICLE: "EDIT_ARTICLE",
    VERIFY_ARTICLE: "VERIFY_ARTICLE",
    APPROVE_ARTICLE: "APPROVE_ARTICLE",
    REJECT_ARTICLE: "REJECT_ARTICLE",

    ARCHIVE_ARTICLE: "ARCHIVE_ARTICLE",
    RESTORE_ARTICLE: "RESTORE_ARTICLE",
    DELETE_ARTICLE: "DELETE_ARTICLE",
    VIEW_ARTICLE_HISTORY: "VIEW_ARTICLE_HISTORY",

    // FAQ
    ADD_FAQ: "ADD_FAQ",
    EDIT_FAQ: "EDIT_FAQ",
    SET_DEFAULT_FAQ: "SET_DEFAULT_FAQ",
    ADD_FAQ_QUESTION: "ADD_FAQ_QUESTION",
    EDIT_FAQ_QUESTION: "EDIT_FAQ_QUESTION",

    // Zgłoszenia
    REPORT_BUG: "REPORT_BUG",
    REPORT_PROPOSAL: "REPORT_PROPOSAL",

    // Tagi
    ADD_TAG: "ADD_TAG",
    EDIT_TAG: "EDIT_TAG",
    DELETE_TAG: "DELETE_TAG",

    // Produkty
    ADD_PRODUCT: "ADD_PRODUCT",
    EDIT_PRODUCT: "EDIT_PRODUCT",
    DELETE_PRODUCT: "DELETE_PRODUCT",

    // Kategorie
    ADD_CATEGORY: "ADD_CATEGORY",
    EDIT_CATEGORY: "EDIT_CATEGORY",
    DELETE_CATEGORY: "DELETE_CATEGORY",

    // Projekty JST
    ADD_JST_PROJECT: "ADD_JST_PROJECT",
    EDIT_JST_PROJECT: "EDIT_JST_PROJECT",
    ADD_JST_SCHOOL: "ADD_JST_SCHOOL",
    EDIT_JST_SCHOOL: "EDIT_JST_SCHOOL",

    // Tematy rozmowy
    ADD_TOPIC: "ADD_TOPIC",
    EDIT_TOPIC: "EDIT_TOPIC",
    DELETE_TOPIC: "DELETE_TOPIC",
    ACCESS_ADMIN_PANEL: "ACCESS_ADMIN_PANEL",
    READ_ONLY: "READ_ONLY",

    // Zabawne wiadomości
    ADD_FUN_MESSAGE: "ADD_FUN_MESSAGE",
    EDIT_FUN_MESSAGE: "EDIT_FUN_MESSAGE",
    DELETE_FUN_MESSAGE: "DELETE_FUN_MESSAGE",
} as const;

export type PermissionType = keyof typeof Permissions;
