export const Roles = {
    ADMIN: "ADMIN",
    MODERATOR: "MODERATOR",
    EDYTOR: "EDYTOR",
    AUTOR: "AUTOR",
    CZYTELNIK: "CZYTELNIK",
} as const;

export type RoleType = keyof typeof Roles;

export const Permissions = {
    // Artykuły
    ADD_ARTICLE: "ADD_ARTICLE",
    EDIT_ARTICLE: "EDIT_ARTICLE",
    VERIFY_ARTICLE: "VERIFY_ARTICLE",
    APPROVE_ARTICLE: "APPROVE_ARTICLE",
    REJECT_ARTICLE: "REJECT_ARTICLE",

    ADD_ARTICLE_ATTACHMENT: "ADD_ARTICLE_ATTACHMENT",
    SET_ARTICLE_PRIORITY: "SET_ARTICLE_PRIORITY",

    ARCHIVE_ARTICLE: "ARCHIVE_ARTICLE",
    RESTORE_ARTICLE: "RESTORE_ARTICLE",
    DELETE_ARTICLE: "DELETE_ARTICLE",
    VIEW_ARTICLE_HISTORY: "VIEW_ARTICLE_HISTORY",
    ACCESS_PENDING_ARTICLES_PANEL: "ACCESS_PENDING_ARTICLES_PANEL",

    // FAQ
    ADD_FAQ: "ADD_FAQ",
    EDIT_FAQ: "EDIT_FAQ",
    DELETE_FAQ: "DELETE_FAQ",
    SET_DEFAULT_FAQ: "SET_DEFAULT_FAQ",
    ADD_FAQ_QUESTION: "ADD_FAQ_QUESTION",
    EDIT_FAQ_QUESTION: "EDIT_FAQ_QUESTION",
    DELETE_FAQ_QUESTION: "DELETE_FAQ_QUESTION",

    // Statystyki użytkoników

    VIEW_USER_STATS: "VIEW_USER_STATS",
    VIEW_USER_STATS_DETAILS: "VIEW_USER_STATS_DETAILS",

    // Zgłoszenia
    SEND_REPORT: "SEND_REPORT",
    ADD_REPORT_COMMENT: "ADD_REPORT_COMMENT",
    MANAGE_REPORT_STATUS: "MANAGE_REPORT_STATUS",

    // Tagi
    ADD_TAG: "ADD_TAG",
    EDIT_TAG: "EDIT_TAG",
    DELETE_TAG: "DELETE_TAG",

    // Produkty
    ADD_PRODUCT: "ADD_PRODUCT",
    EDIT_PRODUCT: "EDIT_PRODUCT",
    DELETE_PRODUCT: "DELETE_PRODUCT",

    // Kategorie
    ADD_CATEGORY: "ADD_CATEGORY",
    EDIT_CATEGORY: "EDIT_CATEGORY",
    DELETE_CATEGORY: "DELETE_CATEGORY",

    // Projekty JST
    ADD_JST_PROJECT: "ADD_JST_PROJECT",
    EDIT_JST_PROJECT: "EDIT_JST_PROJECT",
    DELETE_JST_PROJECT: "DELETE_JST_PROJECT",
    ADD_JST_SCHOOL: "ADD_JST_SCHOOL",
    EDIT_JST_SCHOOL: "EDIT_JST_SCHOOL",
    DELETE_JST_SCHOOL: "DELETE_JST_SCHOOL",

    // Tematy rozmowy
    ADD_TOPIC: "ADD_TOPIC",
    EDIT_TOPIC: "EDIT_TOPIC",
    DELETE_TOPIC: "DELETE_TOPIC",
    ACCESS_ADMIN_PANEL: "ACCESS_ADMIN_PANEL",
    READ_ONLY: "READ_ONLY",

    // Zabawne wiadomości
    ADD_FUN_MESSAGE: "ADD_FUN_MESSAGE",
    EDIT_FUN_MESSAGE: "EDIT_FUN_MESSAGE",
    DELETE_FUN_MESSAGE: "DELETE_FUN_MESSAGE",

    // Kolekcje

    ADD_COLLECTION: "ADD_COLLECTION",
    JOIN_COLLECTION: "JOIN_COLLECTION",
} as const;

export type PermissionType = keyof typeof Permissions;
