import {
    FaCrown,
    FaUserTie,
    FaEye,
    FaUser,
    FaBomb,
    FaCat,
    FaMedal,
    FaGrin,
    FaDharmachakra,
    FaChessQueen,
    FaBiohazard,
    FaHands,
    FaCloud,
    FaCannabis,
    FaFistRaised,
    FaChessRook,
    FaTrophy,
    FaRebel,
    FaStudiovinari,
    FaRocket,
    FaHammer,
    FaPaperPlane,
    FaYinYang,
    FaUserSecret,
} from "react-icons/fa";

export const ICON_MAP = {
    FaUser,
    FaCrown,
    FaUserTie,
    FaEye,
    FaYinYang,
    FaUserSecret,
    FaBomb,
    FaCat,
    FaMedal,
    FaGrin,
    FaDharmachakra,
    FaChessQueen,
    FaBiohazard,
    FaHands,
    FaCloud,
    FaCannabis,
    FaFistRaised,
    FaChessRook,
    FaTrophy,
    FaRebel,
    FaStudiovinari,
    FaRocket,
    FaHammer,
    FaPaperPlane,
} as const;

export type IconKey = keyof typeof ICON_MAP;

export const ICON_KEYS = (Object.keys(ICON_MAP) as IconKey[]).filter((key) => key !== "Users");
