name: Deploy

on:
    push:
        branches:
            - "dev"

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Build and push Docker image
              run: |
                  echo '{ "insecure-registries": ["79.187.49.90","79.187.49.90:32711"] }' | sudo tee /etc/docker/daemon.json
                  sudo systemctl restart docker

                  cat <<EOF > .env
                  NODE_ENV=development
                  PORT=5000
                  APP_ORIGIN=https://baza-wiedzy-f.kiszczyc.pl
                  JWT_SECRET=${{ secrets.JWT_SECRET }}
                  SOCKET_PORT=4005
                  JWT_REFRESH_SECRET=${{ secrets.JWT_REFRESH_SECRET }}
                  EMAIL_SENDER=asd@dupa.pl
                  EMAIL_SENDER_PASSWORD="asdasdasd"
                  EMAIL_SERVICE=gmail
                  EMAIL_SERVICE_HOST=smtp.gmail.com
                  RESEND_API_KEY=dupa
                  DEFAULT_TEMP_PASSWORD=${{ secrets.DEFAULT_TEMP_PASSWORD }}
                  ADMIN_DEFAULT_PASSWORD=${{ secrets.ADMIN_DEFAULT_PASSWORD }}
                  ADMIN_DEFAULT_EMAIL=${{ secrets.ADMIN_DEFAULT_EMAIL }}
                  UPLOADS_ROOT=./uploads
                  LOG_LVL ="debug"
                  MONGO_URI=${{ secrets.MONGO_URI }}
                  EOF

                  echo "Building image"
                  docker build -t ${{ vars.APPLICATION_NAME }}:latest .

                  echo "Tagging image"
                  docker tag ${{ vars.APPLICATION_NAME }}:latest ${{ vars.REGISTRY }}/${{ vars.APPLICATION_NAME }}:latest

                  echo "Pushing image"
                  docker push ${{ vars.REGISTRY }}/${{ vars.APPLICATION_NAME }}:latest
